# Конфигурация плагина "Вырасти сад"

# Экономика
economy:
  # Начальный капитал игрока (в рублях)
  starting_balance: 10
  
  # Цены на семена
  seed_prices:
    wheat: 2
    carrot: 3
    potato: 3
    beetroot: 2
    pumpkin: 5
    melon: 5
  
  # Цены продажи урожая
  crop_prices:
    wheat: 5
    carrot: 8
    potato: 8
    beetroot: 6
    pumpkin: 15
    melon: 15
  
  # Стоимость расширения участка (за блок)
  plot_expansion_cost: 1
  
  # Стоимость автоматической поливки (в день)
  auto_watering_cost: 5
  
  # Стоимость удобрений
  fertilizer_costs:
    growth_speed: 10
    crop_size: 15

# Участки
plots:
  # Область размещения участков
  area_start_x: 198
  area_end_x: 314
  area_start_z: 1334
  area_end_z: 1467
  area_height: 62
  
  # Размеры участков
  initial_size: 15
  max_size: 30
  
  # Расстояния
  path_width: 2
  fence_spacing: 1
  
  # Мир для участков
  world: "world"

# Растения
plants:
  wheat:
    growth_time: 30  # секунды
    stages: 8
  carrot:
    growth_time: 45
    stages: 8
  potato:
    growth_time: 45
    stages: 8
  beetroot:
    growth_time: 35
    stages: 4
  pumpkin:
    growth_time: 120
    stages: 4
  melon:
    growth_time: 120
    stages: 4

# Поливка
watering:
  # Время действия ручного полива (в секундах)
  manual_duration: 3600  # 1 час
  
  # Интервал автоматической поливки (в секундах)
  auto_interval: 1800    # 30 минут

# Сохранение
storage:
  # Интервал автосохранения (в секундах)
  auto_save_interval: 300  # 5 минут
  
  # Формат файлов данных
  format: "json" 