# Конфигурация плагина "Вырасти сад"

# Основные настройки
world_name: "world"
plot_size: 15
max_plot_size: 60
initial_balance: 10
expand_cost: 5

# Настройки посадки
only_custom_seeds_on_plots: true
allow_vanilla_seeds_outside: false

# Цены на семена
seed_prices:
  wheat: 5
  carrot: 8
  potato: 8
  beetroot: 6
  pumpkin: 15
  melon: 15

# Цены на урожай
crop_prices:
  wheat: 8
  carrot: 12
  potato: 12
  beetroot: 10
  pumpkin: 25
  melon: 25

# Время роста растений (в секундах)
crop_growth_times:
  wheat: 30
  carrot: 45
  potato: 45
  beetroot: 35
  pumpkin: 120
  melon: 120

# Кастомные растения
custom_plants:
  golden_tree:
    name: "🌳 Золотое дерево"
    seed_material: "GOLD_INGOT"
    plant_material: "OAK_SAPLING"
    harvest_material: "GOLDEN_APPLE"
    seed_name: "Золотые семена дерева"
    seed_lore:
      - "§7Семена мистического золотого дерева"
      - "§7Время роста: §e5 минут"
      - "§7Цена: §e50 рублей"
      - "§7Урожай: §eЗолотые яблоки"
      - "§7Особенность: §eДает золотые яблоки"
    growth_time: 300
    harvest_amount: 3
    price: 50
    
  crystal_rose:
    name: "💎 Кристальная роза"
    seed_material: "AMETHYST_SHARD"
    plant_material: "ROSE_BUSH"
    harvest_material: "AMETHYST_SHARD"
    seed_name: "Кристальные семена розы"
    seed_lore:
      - "§7Семена сияющей кристальной розы"
      - "§7Время роста: §e3 минуты"
      - "§7Цена: §e35 рублей"
      - "§7Урожай: §eКристальные лепестки"
      - "§7Особенность: §eСветится в темноте"
    growth_time: 180
    harvest_amount: 5
    price: 35
    
  fire_pumpkin:
    name: "🔥 Огненная тыква"
    seed_material: "BLAZE_POWDER"
    plant_material: "PUMPKIN"
    harvest_material: "BLAZE_POWDER"
    seed_name: "Огненные семена тыквы"
    seed_lore:
      - "§7Семена пылающей тыквы"
      - "§7Время роста: §e4 минуты"
      - "§7Цена: §e40 рублей"
      - "§7Урожай: §eОгненные тыквы"
      - "§7Особенность: §eПоджигает врагов"
    growth_time: 240
    harvest_amount: 2
    price: 40
    
  ice_berry:
    name: "❄️ Ледяная ягода"
    seed_material: "ICE"
    plant_material: "SWEET_BERRIES"
    harvest_material: "ICE"
    seed_name: "Ледяные семена ягоды"
    seed_lore:
      - "§7Семена замороженной ягоды"
      - "§7Время роста: §e2 минуты"
      - "§7Цена: §e25 рублей"
      - "§7Урожай: §eЛедяные ягоды"
      - "§7Особенность: §eЗамораживает врагов"
    growth_time: 120
    harvest_amount: 4
    price: 25
    
  electric_wheat:
    name: "⚡ Электрическая пшеница"
    seed_material: "REDSTONE"
    plant_material: "WHEAT"
    harvest_material: "REDSTONE"
    seed_name: "Электрические семена пшеницы"
    seed_lore:
      - "§7Семена заряженной пшеницы"
      - "§7Время роста: §e90 секунд"
      - "§7Цена: §e30 рублей"
      - "§7Урожай: §eЭлектрическая пшеница"
      - "§7Особенность: §eУдаряет током"
    growth_time: 90
    harvest_amount: 6
    price: 30
    
  rainbow_flower:
    name: "🌈 Радужный цветок"
    seed_material: "ORANGE_DYE"
    plant_material: "SUNFLOWER"
    harvest_material: "ORANGE_DYE"
    seed_name: "Радужные семена цветка"
    seed_lore:
      - "§7Семена разноцветного цветка"
      - "§7Время роста: §e6 минут"
      - "§7Цена: §e60 рублей"
      - "§7Урожай: §eРадужные лепестки"
      - "§7Особенность: §eМеняет цвет"
    growth_time: 360
    harvest_amount: 8
    price: 60 