name: GardenPlugin
version: '${project.version}'
main: com.minecraft.garden.GardenPlugin
api-version: '1.21'
authors: [YourName]
description: Мини-игра "Вырасти сад" для Minecraft сервера
website: https://github.com/yourusername/minecraft-garden-plugin

commands:
  garden:
    description: Главная команда для управления садом
    usage: /garden [create|plot|tp|shop|sell|invite|expand|help]
    aliases: [g, garden]
    permission: garden.use

permissions:
  garden.use:
    description: Разрешает использовать команды сада
    default: true
  garden.admin:
    description: Административные команды сада
    default: op 