name: FarmerEconomist
version: '${project.version}'
main: com.github.d88a.farmereconomist.FarmerEconomist
api-version: '1.21'
author: d88a
description: 'Плагин «Фермер-Экономист» для сервера Minecraft.'

commands:
  ogorod:
    description: Управление участками.
    aliases: [plot]
    usage: |
      /ogorod set_start - Установить начальную точку сетки.
      /ogorod set_config <параметр> <значение> - Настроить параметры участков.
      /ogorod get - Получить новый участок.
      /ogorod home - Телепортироваться на свой участок.
  balance:
    description: Проверить свой баланс.
    aliases: [money]
  eco:
    description: Управление экономикой (для администраторов).
    aliases: [economy]
    permission: farmereconomist.admin.eco
    usage: |
      /eco give <игрок> <сумма>
      /eco take <игрок> <сумма>
      /eco set <игрок> <сумма>
  fermer:
    description: Взаимодействие с NPC-фермером.
    usage: |
      /fermer - Телепортироваться к фермеру.
      /fermer set_npc - Установить позицию NPC (для администраторов).
  stats:
    description: Просмотр статистики фермерства.
    aliases: [statistics, profile]
    usage: |
      /stats - Показать свою статистику
      /stats <игрок> - Показать статистику игрока (для администраторов)
  event:
    description: Управление событиями фермерства.
    aliases: [events]
    usage: |
      /event status - Показать текущее событие
      /event list - Список всех событий
      /event start <событие> - Запустить событие (для администраторов)
      /event stop - Остановить текущее событие (для администраторов)

permissions:
  farmereconomist.admin.eco:
    description: Доступ к командам управления экономикой
    default: op
  farmereconomist.admin.stats:
    description: Доступ к просмотру статистики других игроков
    default: op
  farmereconomist.admin.event:
    description: Доступ к управлению событиями
    default: op 