name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Purge Maven local repository
        run: mvn dependency:purge-local-repository

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Rename artifact for release
        run: mv ./target/minecraft-garden-plugin-1.0-SNAPSHOT.jar ./target/FarmerEconomist.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ github.run_number }}
          name: Build ${{ github.run_number }}
          prerelease: true
          files: ./target/FarmerEconomist.jar 