name: Deploy Plugin to SFTP

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Deploy to SFTP server
      uses: cross-the-world/scp-pipeline@v1.1.0
      with:
        host: ${{ secrets.SFTP_SERVER }}
        port: 2022
        user: ${{ secrets.SFTP_USERNAME }}
        pass: ${{ secrets.SFTP_PASSWORD }}
        connect_timeout: 10s
        local: "./target/*.jar"
        remote: "/root/aurorix/plugins/"
        sftp_only: true 