name: Deploy Plugin to SFTP

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: ./target/*.jar

    - name: Deploy to SFTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        protocol: sftp
        port: 2022
        local-dir: ./target/
        server-dir: /root/aurorix/plugins/
        exclude: |
          **/*.md
          **/*.txt 