name: Deploy Plugin to SFTP

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Deploy to SFTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: e1.aurorix.net
        username: d88a.51844846
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 2022
        local-dir: ./target/
        server-dir: ./plugins/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.hg*
          **/.hg*/**
          **/.svn/**
          **/.DS_Store
          **/Thumbs.db
          **/.vs/**
          **/.vscode/**
          **/*.log
          **/*.tmp
          **/*.temp 