name: Deploy Plugin to SFTP

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: garden-plugin
        path: ./target/*.jar
        if-no-files-found: error 
    - name: Create Release and Upload JAR
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Build
        body: Автоматическая сборка плагина Minecraft Garden Plugin
        files: ./target/*.jar
      env:
        # Используйте PAT с правами repo/public_repo, добавьте его как секрет GH_PAT
        GITHUB_TOKEN: ${{ secrets.GH_PAT }} 