name: Deploy Plugin to SFTP

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package

    - name: Upload plugin artifact
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: ./target/*.jar

    - name: Show JAR file size
      run: ls -lh ./target/*.jar

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Deploy to SFTP server
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_PORT: ${{ secrets.SFTP_PORT || 2022 }}
      run: bash ./deploy_sftp.sh 