name: Deploy Plugin to SFTP

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Deploy to SFTP server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 2022
        source: "./target/*.jar"
        target: "/root/aurorix/plugins/"
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.hg*
          **/.hg*/**
          **/.svn/**
          **/.DS_Store
          **/Thumbs.db
          **/.vs/**
          **/.vscode/**
          **/*.log
          **/*.tmp
          **/*.temp 